#!/bin/bash
# fetch_secrets.sh
# Pulls all app secrets from SSM Parameter Store and writes .env
# Run this on EC2 before docker compose up — no manual .env copy needed.
#
# Usage:
#   chmod +x scripts/fetch_secrets.sh
#   ./scripts/fetch_secrets.sh
#   ./scripts/fetch_secrets.sh --env staging   (override environment)

set -euo pipefail

PROJECT="utility-billing-ai"
ENVIRONMENT="${1:-prod}"
REGION="${AWS_DEFAULT_REGION:-us-east-2}"
OUTPUT_FILE="${2:-.env}"
SSM_PATH="/${PROJECT}/${ENVIRONMENT}/"

echo "Fetching secrets from SSM: ${SSM_PATH} (region: ${REGION})"

# Pull all parameters under the path
PARAMS=$(aws ssm get-parameters-by-path \
  --path "${SSM_PATH}" \
  --with-decryption \
  --recursive \
  --region "${REGION}" \
  --query "Parameters[*].[Name,Value]" \
  --output text)

if [ -z "$PARAMS" ]; then
  echo "ERROR: No parameters found at ${SSM_PATH}"
  echo "Make sure terraform apply was run and IAM role has ssm:GetParametersByPath permission."
  exit 1
fi

# Write .env file
echo "# Auto-generated by fetch_secrets.sh — do not edit manually" > "${OUTPUT_FILE}"
echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "${OUTPUT_FILE}"
echo "" >> "${OUTPUT_FILE}"

while IFS=$'\t' read -r name value; do
  # Strip the SSM path prefix to get just the key name
  key="${name#${SSM_PATH}}"
  echo "${key}=${value}" >> "${OUTPUT_FILE}"
done <<< "$PARAMS"

echo ".env written to ${OUTPUT_FILE} ($(grep -c '=' "${OUTPUT_FILE}") variables)"
echo "Done."
